name: instagram_clone_firebase_getx
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4


  image_picker: ^1.0.7
  cached_network_image: ^3.2.2
  eva_icons_flutter: ^3.1.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0
  http: ^1.2.1
  flutter_local_notifications: ^17.0.1
  get: ^4.6.6



  platform_device_id_v3: ^1.0.0
  firebase_messaging: ^14.8.0
  shared_preferences: ^2.0.15
  logger: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
